name: cShortcut
main: me.chaseoes.cshortcut.CShortcut
version: 1.3
description: Create command shortcuts.
commands:
  cshortcut:
    description: Central command for cShortcut.
    permission: cshortcut.reload
    usage: /cshortcut reload
